# `=== Atelier Pandas ===`

### `Partie 1 - Series`

#### `1.1 Création d'une Series contenant 4 températures`

In [1]:
import pandas as pd

# Creation de la serie a partir d'une list
temperatures = [25, 34, 23, 40]
serie = pd.Series(temperatures)
serie

0    25
1    34
2    23
3    40
dtype: int64

#### `1.2 Affichage de l'index`

In [2]:
serie.index

RangeIndex(start=0, stop=4, step=1)

#### `1.3 Affichage de la 1ère valeur`

In [3]:
serie[0]

np.int64(25)

#### `1.4 Affichage de la dernière valeur`

In [4]:
serie.iloc[-1]

np.int64(40)

#### `1.5 Création, de deux façon différentes, d'une Series de 4 températures avec comme index les heures demesure 12h, 13h, 14h et 15h`

In [5]:
# Methode 1: a partir d'un dictionnaire
dict_temp = {
     "12h": 34,
     "13h": 23,
     "14h": 40,
     "15h": 37
}
serie_1 = pd.Series(dict_temp)
serie_1

12h    34
13h    23
14h    40
15h    37
dtype: int64

In [6]:
# Methode 2: A partir d'une liste,
indexes = ["12h", "13h", "14h", "15h"] 
serie_2 = pd.Series(temperatures, index=indexes)
serie_2

12h    25
13h    34
14h    23
15h    40
dtype: int64

#### `1.6 Affichage de la 1ère et la dernière valeur`

In [7]:
#
serie_2.iloc[[0, -1]]

12h    25
15h    40
dtype: int64

### `=== Partie 2 – DataFrame ===`

#### `2.1 Création et affichage du dataframe df_test à partir du dictionnaire suivant`


data = {
"capteur": ["C001", "C002", "C003"],
"temperature": [24.5, 25.1, 26.3],
"humidite": [65, 67, 70]

In [8]:
data = {
     "capteur": ["C001", "C002", "C003"],
     "temperature": [24.5, 25.1, 26.3],
     "humidite": [65, 67, 70]
}

df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

#### `2.2 Importation du dataset mesures_capteurs.csv dans le dataframe df`

In [9]:
df = pd.read_csv("../data/mesures_capteurs.csv")
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

#### `2.3 Affichage des dimensions de df`

In [10]:
print(f"Dimensions du dataset: {df.shape}")

Dimensions du dataset: (605, 9)

## `Partie 3 – Exploration`

#### `3.1 Affichage des premières lignes`

In [11]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

#### `3.2 Affichage des 10 premières lignes`

In [12]:
# 10 première ligne du dataset
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

#### `3.3 Affichage des dernières lignes`

In [13]:
# Dernière ligne du dataset
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

#### `3.4 Affichage du nombre de lignes`

In [14]:
# Nombre de ligne du dataset
print(f"Nombre de ligne: {df.shape[0]}")

Nombre de ligne: 605

#### `3.5 Affichage du nombre de colonnes`

In [15]:
# Nombre de colonne du dataset
print(f"Nombre de colonne: {df.shape[1]}")

Nombre de colonne: 9

#### `3.6 Afficher les noms des colonnes`

In [16]:
# Nom de colonne
print(f"Noms des colonnes: \n{df.columns.values}")

Noms des colonnes:
<StringArray>
[   'id_mesure',   'date_heure',   'id_capteur',     'batiment',
  'temperature',     'humidite',     'pression', 'consommation',
         'etat']
Length: 9, dtype: str

#### `3.7 Affichage des informations générales`

In [17]:
print(f"Informations du Dataset: \n {df.info()}")

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB
Informations du Dataset:
 None

#### `3.8 Affichage des statistiques descriptives`

In [18]:
print(f"Statistiques descriptives: \n {df.describe()}")

Statistiques descriptives:
        temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

## `Partie 4 – Sélection`

#### `4.1 Sélection la colonne "temperature"`

In [19]:
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

#### `4.2 Sélection des colonnes "temperature", "humidite", "pression" et "consommation"`

In [20]:
df[["temperature", "humidite", "pression", "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

### `4.3 Sélection des 5 premières lignes avec loc`

In [21]:
df.loc[0:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### `4.4 Sélection des 5 premières lignes et les 4 premières colonnes avec iloc`

In [22]:
df.iloc[:5, :4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

## `Partie 5 – Manipulation des colonnes`

### `5.1 Ajouter la colonne "temperature_fahrenheit"`

In [23]:
df["temperature_fahrenheit"] = (df["temperature"] * 1.8) +32
df["temperature_fahrenheit"]

0      77.828
1      75.200
2      78.476
3      82.814
4      69.044
        ...
600    74.606
601    75.812
602    74.714
603    76.694
604    62.636
Name: temperature_fahrenheit, Length: 605, dtype: float64

### `5.2 Ajouter la colonne "niveau_temperature" pour catégoriser la température en "Élevée" (température > 30) ou "Normale". `

In [31]:
import numpy as np

df["nouveau_temperature"] = np.where(df["temperature"] > 30, "Elevée", "Normal")
df["nouveau_temperature"]

0      Normal
1      Normal
2      Normal
3      Normal
4      Normal
        ...
600    Normal
601    Normal
602    Normal
603    Normal
604    Normal
Name: nouveau_temperature, Length: 605, dtype: str

### `5.3 Renommage de la colonne "humidite" en "humidite_relative"`

In [32]:
df = df.rename(columns = {"humidite":"humidite_relative"})
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,temperature_fahrenheit,nouveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828,Normal
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200,Normal
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476,Normal
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,82.814,Normal
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,69.044,Normal
...,...,...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK,74.606,Normal
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK,75.812,Normal
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK,74.714,Normal
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK,76.694,Normal
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK,62.636,Normal

### `5.4 Suppression de la colonne "temperature_fahrenheit"`

In [33]:
df = df.drop(columns=["temperature_fahrenheit"])
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,nouveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,Normal
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,Normal
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,Normal
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,Normal
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,Normal
...,...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK,Normal
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK,Normal
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK,Normal
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK,Normal
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK,Normal

## `Partie 6 – Filtrage`

#### `6.1 Récupération des lignes telles que température > 30`

In [34]:
df[df['temperature'] > 30]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,nouveau_temperature
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK,Elevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Elevée
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Elevée
63,M0064,2026-01-07 15:00:00,C004,B002,31.19,55.13,1011.04,264.98,OK,Elevée
79,M0275,2026-01-16 10:00:00,C011,B004,31.74,69.95,1020.79,335.89,OK,Elevée
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK,Elevée
103,M0311,2026-01-17 22:00:00,C011,B004,30.83,54.99,1026.47,256.11,OK,Elevée
112,M0149,2026-01-11 04:00:00,C005,B002,31.46,48.48,1002.75,210.94,OK,Elevée
118,M0365,2026-01-20 04:00:00,C005,B002,32.90,65.91,1027.28,246.08,ALERTE,Elevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Elevée
137,M0076,2026-01-08 03:00:00,C004,B002,31.18,49.66,1019.91,215.22,OK,Elevée
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK,Elevée
146,M0118,2026-01-09 21:00:00,C010,B004,30.32,NaN,1015.78,261.68,OK,Elevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Elevée
168,M0276,2026-01-16 11:00:00,C012,B004,30.39,71.14,1017.79,303.38,OK,Elevée
169,M0546,2026-01-27 17:00:00,C006,B002,32.36,67.34,998.10,184.89,ALERTE,Elevée
174,M0405,2026-01-21 20:00:00,C009,B003,31.74,47.23,1015.59,115.79,OK,Elevée
210,M0588,2026-01-29 11:00:00,C012,B004,31.51,72.49,1018.21,307.97,OK,Elevée
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Elevée
224,M0303,2026-01-17 14:00:00,C003,B001,30.84,67.98,1020.09,157.99,OK,Elevée
243,M0416,2026-01-22 07:00:00,C008,B003,30.16,54.00,1012.18,875.00,ERREUR,Elevée
246,M0312,2026-01-17 23:00:00,C012,B004,30.13,65.68,1009.70,198.65,OK,Elevée
251,M0114,2026-01-09 17:00:00,C006,B002,31.85,85.77,1013.56,237.21,ALERTE,Elevée
257,M0378,2026-01-20 17:00:00,C006,B002,31.99,66.32,1013.54,254.67,OK,Elevée
264,M0191,2026-01-12 22:00:00,C011,B004,30.75,71.35,1018.92,308.66,OK,Elevée
274,M0046,2026-01-06 21:00:00,C010,B004,30.92,67.19,1009.71,329.78,OK,Elevée
280,M0585,2026-01-29 08:00:00,C009,B003,31.30,73.35,1021.40,187.98,OK,Elevée
322,M0120,2026-01-09 23:00:00,C012,B004,30.19,53.58,1013.05,396.90,ALERTE,Elevée
356,M0574,2026-01-28 21:00:00,C010,B004,30.61,60.73,1022.32,321.75,OK,Elevée
362,M0396,2026-01-21 11:00:00,C012,B004,30.57,63.47,1017.40,248.36,OK,Elevée
385,M0126,2026-01-10 05:00:00,C006,B002,30.09,73.95,1007.24,162.39,OK,Elevée
398,M0514,2026-01-26 09:00:00,C010,B004,30.48,93.57,1015.93,306.24,ALERTE,Elevée
401,M0586,2026-01-29 09:00:00,C010,B004,31.44,63.10,996.56,271.51,OK,Elevée
404,M0598,2026-01-29 21:00:00,C010,B004,30.37,64.55,997.31,311.77,OK,Elevée
417,M0432,2026-01-22 23:00:00,C012,B004,30.38,65.98,1005.48,256.18,OK,Elevée
437,M0286,2026-01-16 21:00:00,C010,B004,32.16,41.80,996.99,255.56,ALERTE,Elevée
438,M0558,2026-01-28 05:00:00,C006,B002,32.56,67.77,1016.88,181.51,ALERTE,Elevée
447,M0170,2026-01-12 01:00:00,C002,B001,31.15,69.20,1016.10,172.49,OK,Elevée
488,M0431,2026-01-22 22:00:00,C011,B004,30.14,51.02,1007.70,366.53,ALERTE,Elevée
492,M0552,2026-01-27 23:00:00,C012,B004,30.24,62.06,1009.35,299.69,OK,Elevée
500,M0062,2026-01-07 13:00:00,C002,B001,30.39,52.13,1004.23,262.66,OK,Elevée
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Elevée
505,M0268,2026-01-16 03:00:00,C004,B002,30.34,64.23,1011.42,179.84,OK,Elevée
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Elevée
541,M0202,2026-01-13 09:00:00,C010,B004,30.86,76.00,1011.94,224.01,OK,Elevée
558,M0346,2026-01-19 09:00:00,C010,B004,30.68,36.33,1010.46,272.59,OK,Elevée

### `6.2 Récupérer uniquement les lignes telles température > 30 et humidité > 70`

In [37]:
df[(df["temperature"] > 30) & (df["humidite_relative"] > 70)]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,nouveau_temperature
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Elevée
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK,Elevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Elevée
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK,Elevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Elevée
168,M0276,2026-01-16 11:00:00,C012,B004,30.39,71.14,1017.79,303.38,OK,Elevée
210,M0588,2026-01-29 11:00:00,C012,B004,31.51,72.49,1018.21,307.97,OK,Elevée
251,M0114,2026-01-09 17:00:00,C006,B002,31.85,85.77,1013.56,237.21,ALERTE,Elevée
264,M0191,2026-01-12 22:00:00,C011,B004,30.75,71.35,1018.92,308.66,OK,Elevée
280,M0585,2026-01-29 08:00:00,C009,B003,31.30,73.35,1021.40,187.98,OK,Elevée
385,M0126,2026-01-10 05:00:00,C006,B002,30.09,73.95,1007.24,162.39,OK,Elevée
398,M0514,2026-01-26 09:00:00,C010,B004,30.48,93.57,1015.93,306.24,ALERTE,Elevée
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Elevée
541,M0202,2026-01-13 09:00:00,C010,B004,30.86,76.00,1011.94,224.01,OK,Elevée